# Site settings
title: Willian Justen - Desenvolvedor Front End
email: willianjustenqui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog de um desenvolvedor Front End e entusiasta de novas tecnologias.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willianjusten.com.br" # the base hostname & protocol for your site
twitter_username: willian_justen
github_username:  willianjusten

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: SÃ©ries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
