backend:
  name: github
  repo: willianjusten/willianjusten.com.br
  branch: master
  site_domain: willianjusten.com.br
media_folder: "assets/img"
publish_mode: editorial_workflow
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Post Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Introduction", name: "introduction", widget: "string"}
      - {label: "Twitter text", name: "twitter_text", widget: "string"}
      - {label: "Main Class", name: "main-class", widget: "select", options: ["jekyll", "css", "js", "html", "svg", "dev", "misc"]}
      - {label: "Color", name: "color", widget: "select", options: [
          { label: "Jekyll", value: "#B31917" },
          { label: "CSS", value: "#2DA0C3" },
          { label: "JS", value: "#D6BA32" },
          { label: "HTML", value: "#EB7728" },
          { label: "SVG", value: "#7D669E" },
          { label: "Dev", value: "#637a91" },
          { label: "Misc", value: "#7AAB13" }
        ]
        }
      - {label: "Tags", name: "tags", widget: "list", default: [""]}
      - {label: "Category", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
